defaults: &defaults
  adapter: postgresql
  username: postgres
  password: mayiyo01
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

development:
  database: multi_tenant_milia
  <<: *defaults

test:
  database: multi_tenant_milia
  <<: *defaults

production:
  database: multi_tenant_milia
  <<: *defaults